title: Family Justice Courts Practice Directions 
theme: minima
plugins:
  - jekyll-seo-tag
  - jekyll-coffeescript
elastic_search:
  index: templateindex
  doctype: bare
environment: DEV
google_analytics: UA-113717369-4
environment: LOCAL
server_LOCAL: http://127.0.0.1:3000
server_DEV: https://datagovsg.github.io/opendoc-bare/
