title: Family Justice Courts Practice Directions 
remote_theme: opendocsg/opendoc-theme
timezone: Asia/Singapore
repository: opendocsg/opendoc-family-justice-courts-practice-directions
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
baseurl: ''
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
google_analytics: UA-113717369-4
styling_options:
  primary_brand_color: '#9f0836'
  logo_path: /assets/images/logo.png
  opendoc_logo_path: /assets/images/logo-full.png
  feedback_url: https://form.gov.sg/forms/govtech/5c0dd61bd4128b001781c84c
