title: Family Justice Courts Practice Directions 
remote_theme: opendocsg/opendoc-theme
plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
timezone: Asia/Singapore
elastic_search:
  index: family-justice-courts-pd
  doctype: bare
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
environment: DEV
google_analytics: UA-113717369-4
styling_options:
  primary_brand_color: '#9f0836'
  logo_path: /assets/images/logo.png
  opendoc_logo_path: /assets/images/logo-full.png
  feedback_url: https://form.gov.sg/forms/govtech/5bbad49058e107000fcf2ad7
